### ISSUE TITLE
windows执行报错

### ISSUE THREAD

**Issue by wooyunvip** [TheKingOfDuck/FileMonitor#1]
环境：win10 +py2
报错如下：
[16:03:42]:Please enter a directory:E:\tools\xxxx\example
[16:03:54]:Unnecessary directory:"E:\tools\xxxx\example"
[16:03:58]:Display directory changes(y or n):y
[16:04:00]:FileMonitor is running...
[16:04:11]:file modified:E:\tools\xxxx\example\test.txt
[16:04:21]:file deleted:E:\tools\xxxxa\example\test.txt
Exception in thread Thread-1:
Traceback (most recent call last):
File "E:\Python\Python27\lib\threading.py", line 801, in __bootstrap_inner
self.run()
File "E:\Python\Python27\lib\site-packages\watchdog\observers\api.py", line 199, in run
self.dispatch_events(self.event_queue, self.timeout)
File "E:\Python\Python27\lib\site-packages\watchdog\observers\api.py", line 368, in dispatch_events
handler.dispatch(event)
File "E:\Python\Python27\lib\site-packages\watchdog\events.py", line 330, in dispatch
_method_mapevent_type
File "fileMonitor.py", line 51, in on_created
print(time.strftime('[%H:%M:%S]:') + "\033[5;32m%s\033[0m" % "file created:{0}".format(event.src_path))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 37-38: ordinal not in range(128)

**Comment by TheKingOfDuck** [comment]
@wooyunvip 感谢反馈,试了下,没能很快解决,难受,容我周末再改了。

![sad](https://user-images.githubusercontent.com/27769271/57221181-c0fc1d80-7030-11e9-9627-2cf9595a59f3.jpg)
