### ISSUE TITLE
mac 报错

### ISSUE THREAD

**Issue by ASDWQad** [TheKingOfDuck/FileMonitor#3]
Traceback (most recent call last):
  File "filemon", line 134, in <module>
  File "/Users/xxxx/Documents/2.CodeAudit/FileMonitor/watchdog/observers/api.py", line 291, in schedule
  File "/Users/xxxx/Documents/2.CodeAudit/FileMonitor/watchdog/observers/kqueue.py", line 443, in __init__
  File "/Users/xxxx/Documents/2.CodeAudit/FileMonitor/watchdog/utils/dirsnapshot.py", line 244, in __init__
  File "/Users/xxxx/Documents/2.CodeAudit/FileMonitor/watchdog/observers/kqueue.py", line 439, in walker_callback
  File "/Users/xxxx/Documents/2.CodeAudit/FileMonitor/watchdog/observers/kqueue.py", line 457, in _register_kevent
  File "/Users/xxxx/Documents/2.CodeAudit/FileMonitor/watchdog/observers/kqueue.py", line 242, in add
  File "/Users/xxxx/Documents/2.CodeAudit/FileMonitor/watchdog/observers/kqueue.py", line 327, in __init__
OSError: [Errno 24] Too many open files: '/Users/xxxx/Documents/6.SourceCode/php/xunruicms_v4.4.2/xunruicms/static/assets/global/img/sidebar_inline_toggler_icon_blue.jpg'

使用main.py，fileMonitor.php 可以用 
fileMonitor.py filemon 就报错。

**Comment by TheKingOfDuck** [comment]
mac上为啥不直接用pip一键安装呢
